# Generated by Django 4.0 on 2021-12-11 23:41

import bot.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_external', models.CharField(max_length=150, unique=True)),
                ('name_internal', models.CharField(max_length=150, unique=True)),
                ('count', models.IntegerField(validators=[bot.validators.validate_positive])),
                ('price', models.IntegerField(validators=[bot.validators.validate_positive])),
            ],
        ),
    ]
