# Generated by Django 4.0 on 2022-01-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
